version: '2'
services:
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - "/express-app/src/adminDashboard/public/images/:/src/adminDashboard/public/images"

  db:
    image: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DatabaseAdmin#12345
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx: 
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  adminer:
    image: adminer
    restart: always
    ports:
      - 4500:8080
    depends_on:
      - db
volumes:
  mysql-data: 
  images:
