version: '2'
services:
  node-app:
    container_name: ghesla-node-container 
    image: ahmedhaggagrady/ghesla
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DatabaseAdmin#12345
    volumes:
      - mysql-data:/var/lib/mysql

  nginx: 
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  adminer:
    image: adminer
    restart: always
    ports:
      - 4500:8080
    depends_on:
      - db
volumes:
  mysql-data: 
