exports.RESERVATION_PENDING = "في الانتظار"
exports.RESERVATION_COMPLETED = "مكتملة"
exports.RESERVATION_DOING = "يقوم به البايكر حاليا"
exports.ALL_RESERVATIONS = "كل الحجوزات"
exports.RESERVATION_PENDING_ID = 1
exports.RESERVATION_DOING_ID = 2
exports.RESERVATION_COMPLETED_ID = 3
exports.POINTS = "نقاط"
exports.BALANCE = "رصيد"