module.exports = {
    INTERNAL_SERVER_ERROR : "INTERNAL_SERVER_ERROR",
    VALIDATION_ERROR : "VALIDATION_ERROR",
    GENERAL_ERROR: "GENERAL_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    SQL_INJECTION_ERROR : "SQL_INJECTION_ERROR"  ,
    UNAUTHORIZED: "UNAUTHORIZED",
    NOTFOUND: "NOTFOUND"
}